name: Publish nestjs-graphql-errors

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS and PNPM
        uses: ./.github/actions/setup
        with:
          node-version: 20.*
          pnpm-version: 9.6.0

      - name: Build package
        run: pnpm build

      - name: Test package
        uses: ./.github/actions/test

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS and PNPM
        uses: ./.github/actions/setup
        with:
          node-version: 20.*
          pnpm-version: 9.6.0

      - name: Build package
        run: pnpm build

      - name: Publish package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
